module.exports = {
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "User",
  "type": "object",
  "properties": {
    "firstName": {
      "type": "string",
      "maxLength": 32,
      "description": "The user's first name."
    },
    "lastName": {
      "type": "string",
      "maxLength": 32,
      "description": "The user's last name."
    },
    "username": {
      "type": "string",
      "maxLength": 16,
      "description": "The user's unique username."
    },
    "about": {
      "type": "string",
      "description": "A brief description about the user."
    },
    "dateRegistered": {
      "type": "string",
      "format": "date-time",
      "description": "The timestamp when the user registered. This field is auto-generated by the database and defaults to the current timestamp."
    },
    "password": {
      "type": "string",
      "maxLength": 256,
      "description": "The user's password."
    },
    "passwordSalt": {
      "type": "string",
      "maxLength": 16,
      "description": "The salt used in conjunction with the user's password."
    },
    "email": {
      "type": "string",
      "maxLength": 64,
      "format": "email",
      "description": "The user's unique email address."
    },
    "avatarURL": {
      "type": "string",
      "maxLength": 64,
      "description": "The URL to the user's avatar image."
    }
  },
  "required": ["username", "email","password"],
  "additionalProperties": false
}